version: 2.1

jobs:
  installation:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: npm install

  test:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Run Tests
          command: npm test

  lint:
    docker:
      - image: node:14
    steps:
      - checkout
      - run:
          name: Install TypeScript and TSLint
          command: npm install -g typescript tslint
      - run:
          name: Run TSLint
          command: tslint -c tslint.json 'src/**/*.ts'

workflows:
  version: 2
  ts-project-workflow:
    jobs:
      - installation
      - test
      - lint
