version: 2.1

jobs:
  installation:
    docker:
      - image: cimg/base:stable
    steps:
      - installation
      - run:
          name: "download dmd"
          command: "wget https://downloads.dlang.org/pre-releases/2.x/2.106.1/dmd_2.106.1~rc.1-0_amd64.deb"
      - run:
          name: "install dmd"
          command: "apt install ./dmd_2.106.1~rc.1-0_amd64.deb"
  
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - unit_test
      - run:
          name: "run test"
          command: "rdmd -unittest rice_cooker_test.d"      

workflows:
  version: 2
  rice-cooker-workflow:
    jobs:
      - installation
      - test
