version: 2.1

jobs:
  installation:
    docker:
      - image: cimg/base:stable
    steps:
      - installation
      - run:
          name: "install gcc"
          command: "apt install -y gcc"
  
  test:
    docker:
      - image: cimg/base:stable
    steps:
      - unit_test
      - run:
          name: "install googletest"
          command: "apt install -y googletest"
      - run:
          name: "build test executable file"
          command: "g++ rice_cooker.cpp rice_cooker_test.cpp -o rice_cooker_test -lgtest -lgtest_main -pthread"
      - run:
          name: "run test"
          command: "./rice_cooker_test"

  lint:
    docker:
      - image: cimg/base:stable
    steps:
      - run:
          name: "install cppcheck"
          command: "apt install -y clang-format"
      - run:
          name: "run cppcheck"
          command: "cppcheck --quiet --error-exitcode=1 rice_cooker.cpp rice_cooker_test.cpp main.cpp rice_cooker.hpp"

workflows:
  version: 2
  rice-cooker-workflow:
    jobs:
      - installation
      - test
      - lint
